export function GET({ site }) {
  const blockedBots = [
    "GPTBot",
    "ChatGPT-User",
    "OAI-SearchBot",
    "Google-Extended",
    "Applebot-Extended",
    "DuckAssistBot",
    "ClaudeBot",
    "Claude-SearchBot",
    "Claude-Web",
    "anthropic-ai",
    "cohere-ai",
    "AI2Bot",
    "CCBot",
    "PerplexityBot",
    "Perplexity-User",
    "Bytespider",
    "Bytedance",
    "Amazonbot",
    "FacebookBot",
    "facebookexternalhit",
    "Meta-ExternalAgent",
    "Diffbot",
    "omgili",
    "omgilibot",
    "Timpibot",
    "YouBot",
    "AhrefsBot",
    "SemrushBot",
    "MJ12bot",
    "DotBot",
    "DataForSeoBot",
    "Barkrowler",
    "BLEXBot",
    "MegaIndex",
    "PetalBot",
    "SeekportBot",
    "SeznamBot",
    "Sogou",
    "Exabot",
    "Qwantify",
    "archive.org_bot",
    "Scrapy",
    "crawler4j",
    "python-requests",
    "Go-http-client",
    "Java",
    "okhttp",
    "curl",
    "wget",
  ];

  const body = [
    ...blockedBots.flatMap((bot) => [
      `User-agent: ${bot}`,
      "Disallow: /",
      "",
    ]),
    "User-agent: *",
    "Disallow: /admin",
    "Disallow: /api/",
    "Disallow: /search.json",
    "Disallow: /content-health.json",
    "Disallow: /content-sync-report.json",
    "Disallow: /content-inventory.json",
    "Disallow: /__robots-canary-hjh",
    "Crawl-delay: 10",
    "Allow: /",
    `Sitemap: ${new URL("/sitemap.xml", site).toString()}`,
    "Content-Signal: search=yes, ai-train=no, ai-input=no",
    "",
  ].join("\n");

  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
